### ISSUE TITLE
Compilation error in Vaadin 24.0.0.alpha6

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/YearMonthCalendarAddon#27]
V24.0.0.alpha6 removes `shadow-focus-mixin` (see https://github.com/vaadin/web-components/pull/5108) which is used by month-calendar-mixin.js

https://github.com/FlowingCode/YearMonthCalendarAddon/blob/7841d093cb392ddf4165c739842b2e7c48c11821/src/main/resources/META-INF/frontend/fc-month-calendar/month-calendar-mixin.js#L23

```
[ERROR] ERROR in ./generated/jar-resources/fc-month-calendar/month-calendar-mixin.js
[ERROR] Module not found: Error: Can't resolve '@vaadin/field-base/src/shadow-focus-mixin.js'
```

Build was working with V24.0.0.alpha5
